name: Update RSS feed.

on:
  push:
    branches:
      - "*"
      - "!gh-pages"

  schedule:
    - cron: "0 * * * *"

jobs:
  publisher:
    name: Generate feed and upload to GitHub pages.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate feed.
        env:
          RF_GITHUB_TOKENS: ${{ secrets.RF_GITHUB_TOKENS }}
          PACKAGE: ayosec/releasesfeed

        run: |
          set -xeuo pipefail

          DEST=build

          mkdir $DEST

          curl -s https://api.github.com/repos/$PACKAGE/releases?per_page=1 \
            | jq -r '
                .[0].assets[]
                  | select(.name | index("linux-x86_64"))
                  | .browser_download_url
              ' \
            | xargs curl -sL \
            | tar zx

          time ./releasesfeed > $DEST/feed.xml

          git add $DEST
          TREE=$(git write-tree --prefix=$DEST)

          COMMIT=$(git -c user.name=bot \
                       -c user.email=bot@actions \
                       commit-tree -m "Update feed" "$TREE")

          git push -f origin "$COMMIT":refs/heads/gh-pages
